### PR TITLE
Add ability to show regular expressions.

### PR DESCRIPTION
**Pull request by DostalTomas**
Hello, 
   I added abilty to display regular expressions, what could be very useful.

Tomas

### CODE REVIEW

**Comment by n-srg** [comment]
@DostalTomas fair point. thank you for diving into this. You know I'm a little bit lazy to set up auto-versioning so could you please bump package version in package.json? (1.0.1 -> 1.0.2) :)

**Comment by DostalTomas** [comment]
Of course, here you are.

Tomas

**Comment by n-srg** [comment]
thank you! glad to see people start using it

**Comment by DostalTomas** [comment]
Yeah, you are welcome.
This plugin is very useful, when you have a complex configuration composed from more partial configurations. 
Best Regards, 
  Tomas

**Comment by n-srg** [comment]
published :rocket:

**Pull request merged**
